owner: ricardomaia 
repo: upptime

sites:
  - name: GenLex
    url: https://genlex.app/

status-website:
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status GENLex
  introTitle: "**GENLex** Status Page"
  introMessage: Página de monitoramento do GENLex App.
  navbar:
    - title: Status GENLex
      href: /
    - title: GENLex App
      href: https://genlex.app/
