owner: xaonix 
repo: status

sites:
  - name: XAONIX.com
    url: https://xaonix.com/
  - name: GenLex
    url: https://genlex.app/
  - name: SignAll
    url: https://signall.app/

status-website:
  favicon: https://raw.githubusercontent.com/XAONIX/status/master/favicon.png
  faviconSvg: https://raw.githubusercontent.com/XAONIX/status/master/favicon.svg
  cname: status.xaonix.com
  theme: night
  logoUrl: https://raw.githubusercontent.com/XAONIX/status/master/xaonix.svg
  name: Status Page
  introTitle: "**Welcome** to the services Status Page"
  introMessage: Please, visit this page whenever you want to check the status of XAONIX services and apps. Here we will also publish information about **scheduled maintenance**.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/XAONIX
   css: ":root{ --up-border-left-color: #4cffaa; --down-border-left-color: #eb8799; } article.up { border-left: 0.7rem solid; } article.down { border-left: 0.7rem solid; }"

i18n:
  footer: XAONIX - Technologies for a new human.
