owner: xaonix 
repo: status

sites:
  - name: XAONIX.com
    url: https://xaonix.com/
  - name: GenLex
    url: https://genlex.app/
  - name: SignAll
    url: https://signall.app/

status-website:
  cname: status.xaonix.com
  theme: dark
  logoUrl: https://raw.githubusercontent.com/XAONIX/status/master/xaonix.svg
  # name: Status Page
  introTitle: "**Status Page**"
  introMessage: XAONIX apps monitoring status page.
  navbar:
    - title: Home
      href: /
    - title: XAONIX Website
      href: https://xaonix.com/
