owner: xaonix 
repo: status

sites:
  - name: XAONIX.com
    url: https://xaonix.com/
  - name: GenLex
    url: https://genlex.app/
  - name: SignAll
    url: https://signall.app/

status-website:
  favicon: https://raw.githubusercontent.com/XAONIX/status/master/favicon.png
  faviconSvg: https://raw.githubusercontent.com/XAONIX/status/master/favicon.svg
  cname: status.xaonix.com
  theme: night
  logoUrl: https://raw.githubusercontent.com/XAONIX/status/master/xaonix.svg
  name: Status Page
  introTitle: "**Welcome**"
  introMessage: This is XAONIX apps monitoring status page.
  navbar:
    - title: Home
      href: /
    - title: Webiste
      href: https://xaonix.com/
    - title: Twitter
      href: https://twitter.com/xaonix_com
    - title: Instagram
      href: https://www.instagram.com/xaonix_com/
