owner: xaonix 
repo: status

sites:
  - name: XAONIX.com
    url: https://xaonix.com/
  - name: GenLex
    url: https://genlex.app/
  - name: SignAll
    url: https://signall.app/

status-website:
  cname: status.xaonix.com
  theme: night
  logoUrl: https://raw.githubusercontent.com/XAONIX/status/master/xaonix.svg
  name: Status Page
  introTitle: "**XAONIX** Service Status Page"
  introMessage: Página de monitoramento do GENLex App.
  navbar:
    - title: Home
      href: /
    - title: XAONIX Website
      href: https://xaonix.com/
